shopping/urls.py
from django.urls import path
from .import views

urlpatterns = [
    path('', views.home, name='home'),
    path('kbouniform', views.kbouniform, name='kbouniform'),
    path('mypage', views.mypage, name='mypage'),
    path('product_list/', views.ProductList.as_view(), name='product_list'),
    path('product_list/<int:pk>/', views.ProductDetail.as_view(),  name='detail'),
    path('product_list/category/<str:slug>/', views.category_page),
    path('product_list/manufacturer/<str:slug>/', views.manufacturer_page),
    path('product_list/<int:pk>/new_comment/', views.new_comment),
    path('product_list/update_comment/<int:pk>/', views.CommentUpdate.as_view()),
    path('product_list/delete_comment/<int:pk>/', views.delete_comment),
    path('product_list/tag/<str:slug>/', views.tag_page),
    path('product_list/create_product/', views.ProductCreate.as_view()),
    path('product_list/update_product/<int:pk>/', views.ProductUpdate.as_view()),
    path('product_list/search/<str:q>/', views.ProductSearch.as_view()),
    ]

shopping_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shopping.urls')),
    path('accounts/', include('allauth.urls')),
    path('markdownx/', include('markdownx.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shopping/models.py
from django.db import models
from django.contrib.auth.models import User
from markdownx.models import MarkdownxField
from markdownx.utils import markdown
import os

class Category(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=50, unique=True, allow_unicode=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f'/product_list/category/{self.slug}/'

    class Meta:
        verbose_name_plural = 'Categories'


class Manufacturer(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=50, unique=True, allow_unicode=True)
    address = models.TextField()
    contact = models.CharField(max_length=20)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f'/product_list/manufacturer/{self.slug}/'




class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f'/product_list/tag/{self.slug}/'


class Product(models.Model):
    name = models.CharField(max_length=200)
    description = MarkdownxField()
    price = models.IntegerField()
    stock = models.IntegerField()
    manufacturer = models.ForeignKey(Manufacturer, null=True, blank=True, on_delete=models.SET_NULL)
    product_image = models.ImageField(upload_to='shopping/images/%Y/%m/%d/', blank=True)
    register_date = models.DateTimeField(auto_now_add=True)
    category = models.ForeignKey(Category, null=True, blank=True, on_delete=models.SET_NULL)
    tags = models.ManyToManyField(Tag, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'[{self.pk}]{self.name} :: {self.author}'

    def get_description_markdown(self):
        return markdown(self.description)


    def get_absolute_url(self):
        return f'/product_list/{self.pk}/'

class Comment(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.author} : {self.content}'

    def get_absolute_url(self):
        return f'{self.product.get_absolute_url()}#comment-{self.pk}'

    def get_avatar_url(self):
        if self.author.socialaccount_set.exists():
            return self.author.socialaccount_set.first().get_avatar_url()
        else:
            return 'https://dummyimage.com/50x50/ced4da/6c757d.jpg'

shopping/forms.py
from .models import Comment
from django import forms

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content', )

shopping/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from .models import Product, Category, Tag, Manufacturer, Comment
from django.core.exceptions import PermissionDenied
from django.utils.text import slugify
from .forms import CommentForm
from django.shortcuts import get_object_or_404
from django.db.models import Q

# Create your views here.
def home(request):
    recent_products = Product.objects.order_by('-pk')[:3]
    return render(request, 'shopping/home.html'
                  , {
                    'recent_products': recent_products,
                  })

def kbouniform(request):
    return render(request, 'shopping/kbouniform.html')

def mypage(request):
    return render(request, 'shopping/mypage.html')

class ProductList(ListView):
    model = Product
    ordering = '-pk'
    paginate_by = 4

    def get_context_data(self, **kwargs):
        context = super(ProductList, self).get_context_data()
        context['categories'] = Category.objects.all()
        context['no_category_product_count'] = Product.objects.filter(category=None).count
        context['manufacturers'] = Manufacturer.objects.all()
        context['no_manufacturer_product_count'] = Product.objects.filter(manufacturer=None).count
        return context


class ProductCreate(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = Product
    fields = ['name', 'description', 'price', 'stock', 'manufacturer', 'product_image', 'category']

    def test_func(self):
        return self.request.user.is_superuser or self.request.user.is_staff

    def form_valid(self, form):
        current_user = self.request.user
        if current_user.is_authenticated and (current_user.is_staff or current_user.is_superuser):
            form.instance.author = current_user
            response = super(ProductCreate, self).form_valid(form)
            tags_str = self.request.POST.get('tags_str')
            if tags_str:
                tags_str = tags_str.strip()
                tags_str = tags_str.replace(',', ';')
                tag_list = tags_str.split(';')
                for t in tag_list:
                    t = t.strip()
                    tag, is_tag_created = Tag.objects.get_or_create(name=t)
                    if is_tag_created:
                        tag.slug = slugify(t, allow_unicode=True)
                        tag.save()
                    self.object.tags.add(tag)
            return response
        else:
            return redirect('/product_list/')

class ProductUpdate(LoginRequiredMixin, UpdateView):
    model = Product
    fields = ['name', 'description', 'price', 'stock', 'manufacturer', 'product_image', 'category']

    template_name = 'shopping/product_update_form.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user == self.get_object().author:
            return super(ProductUpdate, self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied

    def form_valid(self, form):
        response = super(ProductUpdate, self).form_valid(form)
        self.object.tags.clear()
        tags_str = self.request.POST.get('tags_str')
        if tags_str:
            tags_str = tags_str.strip()
            tags_str = tags_str.replace(',', ';')
            tags_list = tags_str.split(';')
            for t in tags_list:
                t = t.strip()
                tag, is_tag_created = Tag.objects.get_or_create(name=t)
                if is_tag_created:
                    tag.slug = slugify(t, allow_unicode=True)
                    tag.save()
                self.object.tags.add(tag)
        return response

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProductUpdate,self).get_context_data()
        if self.object.tags.exists:
            tag_str_list = list()
            for t in self.object.tags.all():
                tag_str_list.append(t.name)
            context['tags_str_default'] =';'.join(tag_str_list)
        return context


class ProductDetail(DetailView):
    model = Product
    def get_context_data(self, **kwargs):
        context = super(ProductDetail, self).get_context_data()
        context['categories'] = Category.objects.all()
        context['no_category_product_count'] = Product.objects.filter(category=None).count
        context['manufacturers'] = Manufacturer.objects.all()
        context['no_manufacturer_product_count'] = Product.objects.filter(manufacturer=None).count
        context['comment_form'] = CommentForm
        return context

def category_page(request, slug):
    if slug == 'no_category':
        category = '미분류'
        product_list = Product.objects.filter(category=None)
    else:
        category = Category.objects.get(slug=slug)
        product_list = Product.objects.filter(category=category)

    return render(request, 'shopping/product_list.html', {
        'product_list': product_list,
        'categories': Category.objects.all(),
        'no_category_product_count': Product.objects.filter(category=None).count,
        'category': category,
        'manufacturers': Manufacturer.objects.all(),
        'no_manufacturer_product_count': Product.objects.filter(manufacturer=None).count,
    })

def manufacturer_page(request, slug):
    if slug == 'no_manufacturer':
        manufacturer = '미분류'
        product_list = Product.objects.filter(manufacturer=None)
    else:
        manufacturer = Manufacturer.objects.get(slug=slug)
        product_list = Product.objects.filter(manufacturer=manufacturer)

    return render(request, 'shopping/product_list.html', {
        'product_list': product_list,
        'manufacturers': Manufacturer.objects.all(),
        'categories': Category.objects.all(),
        'no_category_product_count': Product.objects.filter(category=None).count(),
        'no_manufacturer_product_count': Product.objects.filter(manufacturer=None).count,
        'manufacturer': manufacturer,
    })


def tag_page(request, slug):
    paginate_by = 4
    tag = Tag.objects.get(slug=slug)
    product_list = tag.product_set.all()
    return render(request, 'shopping/product_list.html', {
        'tag': tag,
        'product_list': product_list,
        'categories': Category.objects.all(),
        'no_category_product_count': Product.objects.filter(category=None).count(),
        'manufacturers': Manufacturer.objects.all(),
        'no_manufacturer_product_count': Product.objects.filter(manufacturer=None).count,
    })

def new_comment(request, pk):
    if request.user.is_authenticated:
        product = get_object_or_404(Product, pk=pk)
        if request.method == 'POST':
            comment_form = CommentForm(request.POST)
            if comment_form.is_valid():
                comment = comment_form.save(commit=False)
                comment.product = product
                comment.author = request.user
                comment.save()
                return redirect(comment.get_absolute_url())
            else:
                return redirect(product.get_absolute_url())
        else:
            raise PermissionDenied


class CommentUpdate(LoginRequiredMixin, UpdateView):
    model = Comment
    form_class = CommentForm

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user == self.get_object().author:
            return super(CommentUpdate, self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied

def delete_comment(request,pk):
    comment = get_object_or_404(Comment, pk=pk)
    product = comment.product
    if request.user.is_authenticated and request.user == comment.author :
        comment.delete()
        return redirect(product.get_absolute_url())
    else:
        PermissionDenied

class ProductSearch(ProductList):
    paginate_by = None

    def get_queryset(self):
        q = self.kwargs['q']
        product_list = Product.objects.filter(Q(name__contains=q) | Q(tags__name__contains=q)).distinct()
        return product_list

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProductSearch, self).get_context_data()
        q = self.kwargs['q']
        context['search_info'] = f'Search: {q} ({self.get_queryset().count()})'
        return context

shopping/templates/shopping/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>KBOUNI</title>
    <link href="{% static 'shopping/css/navbar.css' %}" rel="stylesheet" type="text/css" media="screen">
    <link href="{% static 'shopping/css/kbouniform.css' %}" rel="stylesheet" type="text/css" media="screen">
    <link href="{% static 'shopping/bootstrap4/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" media="screen">
    <script src="https://kit.fontawesome.com/인증키를 입력해주세요.js" crossorigin="anonymous"></script>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>

</head>
<body>
{% include 'shopping/navbar.html' %}
<div class="container">
    <div class = "row">
        <div class="col-md-6 col-lg-12" id="main-area">
            {% block main_area %}
            {% endblock %}
        </div>
    </div>
</div>
    {% block content %}
    {% endblock %}

{% include 'shopping/footer.html' %}
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>


</body>
</html>

shopping/templates/shopping/comment_form.html
{% extends 'shopping/base.html' %}
{% load crispy_forms_tags %}
{% block head_title %}
    댓글 수정하기
{% endblock %}
{% block main_area %}
    <h1>댓글 수정하기</h1>
    <hr/>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
            {{form| crispy}}
        <button type = "submit" class="btn btn-primary float-right">등록</button>
    </form>
{% endblock %}

shopping/templates/shopping/footer.html
<footer class="py-3 text-black" style="background-color:#F2F2F2" >
  <div class="container text-center">

      <p> <h5><strong>(주)KBOUNIFORM</strong></h5>주소: 서울특별시 서초구 강남대로<br>고객센터 TEL: 1688-0000<br>
      <small>Copyright &copy; KBOUNIFORM Designed by GAYOUNG</small></p>

  </div>
</footer>

shopping/templates/shopping/home.html
{% extends 'shopping/base.html' %}
{% load static %}
{% block content %}


<div class="container">
    <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="{% static 'shopping/image/1.jpg' %}" class="d-block w-100" alt="First">
            </div>
            <div class="carousel-item">
                <img src="{% static 'shopping/image/2.jpg' %}" class="d-block w-100" alt="Second">
            </div>
            <div class="carousel-item">
                <img src="{% static 'shopping/image/3.jpg' %}" class="d-block w-100" alt="Third">
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>

    <div>
        <div class="text-center text-black">
            <h5>KBO 10개 구단의 유니폼을 KBO UNIFORM에서 만나보세요</h5>
        </div>
        <h2>NEW</h2>
        <p>최근 등록된 3개의 상품입니다</p>
        <div class="py-0">
            <div class="container px-4 px-lg-5 mt-5">
                <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                    {% for p in recent_products %}
                    <div class="col mb-5">
                        <div class="card h-100">
                            <!-- Product image-->
                            <img src="{{p.product_image.url}}" class="card-img-top" alt="{{p}}의 product_image">
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">{{ p.name }}</h5>
                                    <!-- Product description-->
                                    <p class="card-text">{{ p.description | truncatechars:50 }}</p>
                                    <!-- Product price-->
                                    <h5>{{ p.price }}원</h5>
                                </div>
                            </div>
                            <!-- Product actions-->
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center"><a class="btn btn-outline-dark mt-auto"
                                                            href="{{p.get_absolute_url}}">상품 상세보기</a></div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>
    {% endblock %}

shopping/templates/shopping/mypage.html
{% extends 'shopping/base.html' %}
{% block content %}
<!-- Header-->
<header class="bg-white py-5">
    <div class="container px-4 px-lg-2 my-1">
        <div class="text-center text-black">
            <h1 class="display-4 fw-bolder"><strong>MY PAGE</strong></h1>
            <p class="lead fw-normal text-black-50 mb-0">{{ user.username }}님의 MY PAGE</p>
        </div>
    </div>
</header>
<section class="margin-for-footer">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <h2><i class="fa-solid fa-user"></i><strong> 회원 정보</strong></h2>
                        <p><strong>Username</strong>: {{user.username}}<br>
                            {% if user.email %}
                            <strong>E-mail</strong>: {{user.email}} </p>
                        {% endif %}
                    </div>
                </div>
                <div class="card">
                    <div class="card-body">
                        <h2><i class="fa-solid fa-comment"></i><strong> 작성한 댓글</strong></h2>
                        {% for comment in user.comment_set.all %}
                        <a href="{{comment.get_absolute_url}}">
                            <div class="card">
                                <div class="card-body">
                                    <small
                                            class="text-muted">
                                        등록: {{ comment.created_at|date:"Y-m-d h:m" }}
                                        {% if comment.created_at != comment.modified_at %}
                                        수정: {{comment.modified_at|date:"Y-m-d h:m"}}
                                        {% endif %}</small>
                                    {{ comment.content | linebreaks }}
                                </div>

                            </div>

                        </a>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>


{% endblock %}

shopping/templates/shopping/product_detail.html
{% extends 'shopping/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<!-- Header-->
<header class="bg-white py-5">
    <div class="container px-4 px-lg-2 my-1">
        <div class="text-center text-black">
            <h1 class="display-4 fw-bolder"><strong>{% if category %} {{ category }} {% endif %}
                {% if manufacturer %} {{ manufacturer }} {% endif %}
                {% if search_info %} {{ search_info }} 검색 결과 {% endif %}
                {% if tag %} <i class="fas fa-tag"></i> {{ tag }} {% endif %} 상품 리스트

            </strong></h1>
            <p class="lead fw-normal text-black-50 mb-0">다양한 유니폼을 만나보세요</p>
        </div>
    </div>
    <div>
        {% for category in categories %}
        <ul class="list-group list-group-horizontal justify-content-center">
            <li class="list-group-item">
                <a class="nav-link" href="{{ category.get_absolute_url }}">{{ category }}
                    ({{ category.product_set.count }})</a></li>
            {% endfor %}
            <li class="list-group-item"><a class="nav-link" href="{% url 'product_list' %}category/no_category">
                미분류({{ no_category_product_count }})</a></li>
        </ul>
    </div>
    <br/>
        <div>
        {% for manufacturer in manufacturers %}
        <ul class="list-group list-group-horizontal justify-content-center">
            <li class="list-group-item">
                <a class="nav-link" href="{{ manufacturer.get_absolute_url }}">{{ manufacturer }}
                    ({{ manufacturer.product_set.count }})</a></li>
            {% endfor %}
            <li class="list-group-item"><a class="nav-link" href="{% url 'product_list' %}manufacturer/no_manufacturer">
                미분류({{ no_manufacturer_product_count }})</a></li>
        </ul>
    </div>

</header>

<!-- Product section-->
<section class="py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="row gx-4 gx-lg-5 align-items-center">
            <div class="col-md-6"><img class="card-img-top mb-5 mb-md-0" src="{{product.product_image.url}}"
                                       alt="{{product.name}}의 image"/></div>
            <div class="col-md-6">
                {% if product.category %}
                <a class="small mb-1 text-dark"  href="{{ product.category.get_absolute_url }}">{{ product.category }}</a>
                {% else %}
                <a class="small mb-1 text-dark" href="{% url 'product_list' %}category/no_category">미분류</a>
                {% endif %}
                {% if user.is_authenticated and user == product.author %}
                <a class="btn btn-outline-dark float-right" href="/product_list/update_product/{{product.pk}}/"
                   role="button">
                    <i class="fas fa-pen">상품 수정하기</i>
                </a>
                {% endif %}
                <h1 class="display-5 fw-bolder"><strong>{{ product.name }}</strong></h1>
                <hr>
                <div class="fs-5 mb-5">
                    <p>상품 등록일 {{ product.register_date|date:"Y-m-d" }}</p>
                    <a class="text-dark" href="{{ product.manufacturer.get_absolute_url }}"><p>제조사 {{ product.manufacturer }}</p></a>
                    <p>제조사 연락처 {{ product.manufacturer.contact }}</p>
                    <p>제조사 주소 {{ product.manufacturer.address }}</p>
                    <p>판매가 <strong>{{ product.price }}원</strong></p>
                    <p>재고 {{ product.stock }}개</p>
                    <hr>
                </div>
                <p class="lead">{{ product.get_description_markdown | safe }}</p>
                {% if product.tags.exists %}
                <i class="fas fa-tag"></i>
                {% for tag in product.tags.iterator %}
                <span class="badge badge-pill badge-light"><a href="{{tag.get_absolute_url}}">{{ tag }}</a></span>
                {% endfor %}
                {% endif %}
                <hr>
                <div>
                    <button class="btn btn-outline-dark flex-shrink-0" type="button">
                        구매하기
                    </button>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- Related items section-->
<section class="py-5 bg-white">
    <div class="container px-4 px-lg-5 mt-5">
        <h2 class="fw-bolder mb-4">Comment</h2>
        <div class="card bg-light">
            <div class="card-body">
                <!-- Comment form-->
                {% if user.is_authenticated %}
                <form class="mb-4" id="comment-form" method="POST"
                      action="{{product.get_absolute_url}}new_comment/">
                    {% csrf_token %}
                    <div class="form-group">
                        {{comment_form | crispy}}
                    </div>
                    <button type="submit" class="btn btn-outline-dark float-right">등록</button>
                    <br>
                </form>
                {% else %}
                <a role="button" class="btn btn-dark btn-block btn-sm" href="#" data-toggle="modal"
                   data-target="#loginModal">
                    로그인한 사용자만 댓글을 작성할 수 있습니다</a>
                <br>
                {% endif %}
                {% if product.comment_set.exists %}
                {% for comment in product.comment_set.iterator %}
                <!-- Single comment-->
                <div class="d-flex" id="comment-{{comment.pk}}">
                    <div class="flex-shrink-0"><img class="rounded-circle"
                                                    src="{{comment.get_avatar_url}}" alt="{{comment.author}}" width="40px"/>
                    </div>
                    <div class="ms-3">
                        <div class="fw-bold">&nbsp;&nbsp;<strong>{{ comment.author.username }}</strong>
                            &nbsp;&nbsp;<small
                                    class="text-muted">
                                등록: {{ comment.created_at|date:"Y-m-d h:m" }}
                                {% if comment.created_at != comment.modified_at %}
                                수정: {{comment.modified_at|date:"Y-m-d h:m"}}
                                {% endif %}</small>
                        </div>
                        <p>{{ comment.content | linebreaks }}</p>
                    </div>

                </div>
                <div>
                    {% if user.is_authenticated and comment.author == user %}
                    <div class="float-right">
                        <a role="button" class="btn btn-small btn-outline-dark"
                           href="/product_list/update_comment/{{comment.pk}}/">
                            수정
                        </a>
                        <a role="button" class="btn btn-small btn-outline-danger float-right"
                           data-toggle="modal" data-target="#deleteModal-{{comment.pk}}"
                           href="#">
                            삭제
                        </a>
                    </div>
                    <!-- Modal -->
                    <div class="modal fade" id="deleteModal-{{comment.pk}}" tabindex="-1"
                         aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLabel">
                                        댓글 삭제</h5>
                                    <button type="button" class="close" data-dismiss="modal"
                                            aria-label="Close"></button>
                                    <span aria-hidden="true">&times;</span>
                                </div>
                                <div class="modal-body">
                                    <del>{{comment|linebreaks}}</del>
                                </div>

                                <div class="modal-footer">
                                    <button type="button" class="btn btn-outline-dark" data-bs-dismiss="modal">취소
                                    </button>
                                    <a role="button" class="btn btn-outline-danger" data-bs-dismiss="modal"
                                       href="/product_list/delete_comment/{{comment.pk}}/">
                                        삭제
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>

                    <br>
                    <br>
                    {% endif %}
                </div>
                {% endfor %}
                {% endif %}

            </div>
        </div>
    </div>
</section>


{% endblock %}

shopping/templates/shopping/product_form.html
{% extends 'shopping/base.html' %}
{% load crispy_forms_tags %}

{% block head_title %} 상품 등록하기 {% endblock %}
{% block main_area %}
<h1>상품 등록하기 </h1>
<hr/>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form | crispy }}
        <div id=div_id_tags_str">
            <label for="id_tags">Tags:</label>
            <input id="id_tags" type="text" name="tags_str" value="{{tags_str_default}}"
                   class="textinput textInput form-control">
        </div>
        <br/>

        <button type = "submit" class="btn btn-outline-dark float-right">등록</button>
    </form>
    {{ form.media }}
{% endblock %}

shopping/templates/shopping/product_update_form.html
{% extends 'shopping/base.html' %}
{% load crispy_forms_tags %}
{% block head_title %} 상품 수정하기 {% endblock %}
{% block main_area %}
<h1>상품 수정하기 </h1>
<hr/>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form | crispy }}
        <div id=div_id_tags_str">
            <label for="id_tags">Tags:</label>
            <input id="id_tags" type="text" name="tags_str" value="{{tags_str_default}}"
                   class="textinput textInput form-control">
        </div>
        <br/>
        <button type = "submit" class="btn btn-outline-dark float-right">수정하기</button>
    </form>
    {{ form.media }}
{% endblock %}